### ISSUE TITLE
If you make A DHS/IRC Server from Labyrinths and attempt to use the mission board it gives an error

### ISSUE THREAD

**Issue by BartholomewIvanel** [Arkhist/Hacknet-Pathfinder#227]
```
[Error  :PathfinderAPI]
Value cannot be null.
Parameter name: text

Source : FNA

System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at Microsoft.Xna.Framework.Graphics.SpriteFont.MeasureString(String
   text) IL<0x000D>

   at Hacknet.Gui.TextItem.doFontLabel(Vector2 pos, String text, SpriteFont
   font, Nullable`1 color, Single widthTo, Single heightTo, Boolean
   centreVertically) IL<0x001B>

   at Hacknet.DLCHubServer.DrawMissionDetailsPanel(Rectangle bounds,
   SpriteBatch sb, ClaimableMission mission) IL<0x014F>

   at Hacknet.DLCHubServer.draw(Rectangle bounds, SpriteBatch sb)
   IL<0x01D9>

   at Hacknet.DisplayModule.doDaemonDisplay() IL<0x006B>
   at Hacknet.DisplayModule.doCommandModule() IL<0x02AE>
   at Hacknet.DisplayModule.Draw(Single t) IL<0x000A>



   at Microsoft.Xna.Framework.Graphics.SpriteFont.MeasureString(String
   text) IL<0x000D>

   at Hacknet.Gui.TextItem.doFontLabel(Vector2 pos, String text, SpriteFont
   font, Nullable`1 color, Single widthTo, Single heightTo, Boolean
   centreVertically) IL<0x001B>

   at Hacknet.DLCHubServer.DrawMissionDetailsPanel(Rectangle bounds,
   SpriteBatch sb, ClaimableMission mission) IL<0x014F>

   at Hacknet.DLCHubServer.draw(Rectangle bounds, SpriteBatch sb)
   IL<0x01D9>

   at Hacknet.DisplayModule.doDaemonDisplay() IL<0x006B>
   at Hacknet.DisplayModule.doCommandModule() IL<0x02AE>
   at Hacknet.DisplayModule.Draw(Single t) IL<0x000A>
 White:Microsoft.Xna.Framework.Graphics.Texture2D
 WhiteDisposed:False
 SmallFont:Microsoft.Xna.Framework.Graphics.SpriteFont
 TinyFont:Microsoft.Xna.Framework.Graphics.SpriteFont
 LineEffectTarget:Target : Microsoft.Xna.Framework.Graphics.RenderTarget2D
TargetDisposed : False
 PostProcessort stuff:Post Processor
 Target : Microsoft.Xna.Framework.Graphics.RenderTarget2D
 TargetDisposed : False
 BTarget : Microsoft.Xna.Framework.Graphics.RenderTarget2D
 BTargetDisposed : False
 DBTarget : Microsoft.Xna.Framework.Graphics.RenderTarget2D
 DBTargetDisposed : False
RESOLUTION:
 1920x1080
Fullscreen: true
 Adapter: Generic PnP Monitor
 Device Name: \\.\DISPLAY1
 Status: Normal
 Extra:
```

This only happens when you attempt to accept or view a mission from the IRC mission board.

**Comment by Fayti1703** [comment]
Do you have a minimal sample that causes this? I cannot reproduce that error in the DLC on the `develop` branch.

**Comment by BartholomewIvanel** [comment]
I figured out that the creator of the extension I was using forgot the add the email port on the mission posting. Somehow Pathfinder was suppressing the error message unless it happened in game. I switched off of it and got the full error message. Very easily fixable.

Thanks @Fayti1703
